### ISSUE TITLE
Merge multiple files

### ISSUE THREAD

**Issue by bkappes** [csm-adapt/confluence#8]
This is simply the recursive application of #7. Merge A + B + C + ... + Y &rarr; Z would merge

A + B &rarr; B<sup>&prime;</sup>

B<sup>&prime;</sup> + C &rarr; C<sup>&prime;</sup>

C<sup>&prime;</sup> + D &rarr; D<sup>&prime;</sup>

...

X<sup>&prime;</sup> + Y &rarr; Z

**Comment by connorweddle2** [comment]
Merge can now take as many inputs as desired and combines them recursively.
